version: '3.3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - APP_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/
      - REDIS_URI=redis://redis:6379/0
      - TZ=Asia/Shanghai
    depends_on:
      - mongodb
      - redis
    networks:
      - ddos-network

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - TZ=Asia/Shanghai
    networks:
      - ddos-network

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - TZ=Asia/Shanghai
    networks:
      - ddos-network

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    environment:
      - TZ=Asia/Shanghai
    networks:
      - ddos-network

  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - TZ=Asia/Shanghai
    depends_on:
      - prometheus
    networks:
      - ddos-network

networks:
  ddos-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  mongodb_data:
  redis_data:
  prometheus_data:
  grafana_data: 